[target.aarch64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install -y cmake pkg-config"]

[target.arm-unknown-linux-gnueabihf]
pre-build = ["apt-get update && apt-get install -y cmake pkg-config"]
